DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS COLOUR;
DROP TABLE IF EXISTS MAKE;
DROP TABLE IF EXISTS SIZE;
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE CATEGORY (
 id INT  PRIMARY KEY,
 name VARCHAR(250) NOT NULL,
 description VARCHAR(250) NOT NULL
);

CREATE TABLE COLOUR (
 id INT  PRIMARY KEY,
 name VARCHAR(250) NOT NULL
);

CREATE TABLE MAKE (
  id INT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

CREATE TABLE SIZE (
  id INT  PRIMARY KEY,
  size VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL
);

CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  categoryId INT NOT NULL,
  FOREIGN KEY (categoryId) references CATEGORY(ID),
  colourId INT NOT NULL,
  FOREIGN KEY (colourId) REFERENCES COLOUR(id),
  makeId INT NOT NULL,
  FOREIGN KEY (makeId) REFERENCES MAKE(id),
  sizeId INT NOT NULL,
  FOREIGN KEY (sizeId) REFERENCES SIZE(id)
);

